"""Coverage for review_pending_patch.py — the human review CLI for propose-only patches.

Focus: the apply/reject → hitl_queue.json resolution loop (a `source: 'reflex_patch'`
pending item created by reflex-engine.ts's _enqueuePendingPatchHitl must not keep
reporting as a pending approval forever once a human has applied or rejected the patch
it names), and that resolution failures never fail the apply/reject itself.
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest


ORDER_SAMURAI = Path(__file__).resolve().parents[1]
_SPEC = importlib.util.spec_from_file_location(
    "review_pending_patch", ORDER_SAMURAI / "bin" / "review_pending_patch.py"
)
assert _SPEC and _SPEC.loader
rpp = importlib.util.module_from_spec(_SPEC)
sys.modules["review_pending_patch"] = rpp
_SPEC.loader.exec_module(rpp)


def _git_repo(tmp_path: Path) -> Path:
    """A one-commit git repo whose tracked file a generated patch will target."""
    repo = tmp_path / "repo"
    repo.mkdir()
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.test"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "test"], cwd=repo, check=True)
    (repo / "target.txt").write_text("before\n", encoding="utf-8")
    subprocess.run(["git", "add", "target.txt"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "init"], cwd=repo, check=True)
    return repo


def _make_patch_content(repo: Path) -> str:
    """A real unified diff against the repo's tracked file, generated by git itself."""
    (repo / "target.txt").write_text("after\n", encoding="utf-8")
    diff = subprocess.run(
        ["git", "diff"], cwd=repo, check=True, capture_output=True, text=True
    ).stdout
    subprocess.run(["git", "checkout", "--", "target.txt"], cwd=repo, check=True)
    return diff


def _queue_item(patch_name: str, item_id: str = "hitl-patch-1") -> dict:
    """A pending item shaped like _enqueuePendingPatchHitl's real output, including a
    directory-with-a-space in the embedded path (the real Order Samurai root has one)."""
    patch_path = f"<REPO_ROOT>/Governance/Order Samurai/state/{patch_name}"
    return {
        "id": item_id,
        "source": "reflex_patch",
        "tier_assigned": "hitl",
        "status": "pending",
        "enqueued_at": "2026-08-01T12:00:00+00:00",
        "approved_at": None,
        "rejected_at": None,
        "rejected_reason": None,
        "executing_at": None,
        "completed_at": None,
        "skill": "/repair",
        "command": "/repair",
        "metric_id": "arts:Test",
        "pillar": "Arts",
        "blast_radius": "repo",
        "reversible": True,
        "consecutive_no_improvement": 0,
        "stuck": False,
        "context": (
            "Validated propose-only remediation patch awaiting review. "
            f"reflex_id=arts:Test skill=/repair patch={patch_path}. "
            "It passed the maker-checker audit and the pytest gate."
        ),
        "backlog_id": None,
    }


@pytest.fixture
def rig(monkeypatch: pytest.MonkeyPatch, tmp_path: Path):
    """Wires review_pending_patch at its module-level paths onto an isolated repo +
    order-samurai-root pair. GOVERNANCE_ROOT is left pointing at the REAL Governance
    package (computed at import time from the real bin/ location) so the queue
    resolution exercises the genuine agentica_core.bushido_engine writer, not a mock.
    """
    repo = _git_repo(tmp_path)
    order_samurai_root = tmp_path / "order_samurai"
    state_dir = order_samurai_root / "state"
    state_dir.mkdir(parents=True)
    monkeypatch.setattr(rpp, "_ROOT", order_samurai_root)
    monkeypatch.setattr(rpp, "STATE_DIR", state_dir)
    monkeypatch.setattr(rpp, "ARCHIVE_APPLIED", state_dir / "patch_archive" / "applied")
    monkeypatch.setattr(rpp, "ARCHIVE_REJECTED", state_dir / "patch_archive" / "rejected")
    monkeypatch.setattr(rpp, "REPO_ROOT", repo)
    return repo, state_dir


def _plant(state_dir: Path, repo: Path, name: str = "pending_remediation_test1.patch") -> Path:
    p = state_dir / name
    p.write_text(_make_patch_content(repo), encoding="utf-8")
    return p


def _write_queue(state_dir: Path, items: list[dict]) -> None:
    (state_dir / "hitl_queue.json").write_text(
        json.dumps({"schema_version": 1, "items": items}), encoding="utf-8"
    )


def test_apply_writes_the_patch_and_marks_the_matching_queue_item_done(rig) -> None:
    repo, state_dir = rig
    patch = _plant(state_dir, repo)
    _write_queue(state_dir, [_queue_item(patch.name)])

    assert rpp.do_apply(patch.name) == 0
    assert (repo / "target.txt").read_text(encoding="utf-8") == "after\n"
    assert (rpp.ARCHIVE_APPLIED / patch.name).is_file()
    assert not patch.exists()

    queue = json.loads((state_dir / "hitl_queue.json").read_text(encoding="utf-8"))
    item = queue["items"][0]
    assert item["status"] == "done"
    assert item["completed_at"] is not None


def test_reject_archives_the_patch_and_marks_the_matching_queue_item_rejected(rig) -> None:
    repo, state_dir = rig
    patch = _plant(state_dir, repo)
    _write_queue(state_dir, [_queue_item(patch.name, "hitl-patch-2")])

    assert rpp.do_reject(patch.name) == 0
    assert (repo / "target.txt").read_text(encoding="utf-8") == "before\n"
    assert (rpp.ARCHIVE_REJECTED / patch.name).is_file()

    queue = json.loads((state_dir / "hitl_queue.json").read_text(encoding="utf-8"))
    item = queue["items"][0]
    assert item["status"] == "rejected"
    assert item["rejected_at"] is not None
    assert item["rejected_reason"]


def test_apply_succeeds_with_no_queue_file_at_all(rig) -> None:
    # No hitl_queue.json planted — nothing to resolve, and that must not be an error.
    repo, state_dir = rig
    patch = _plant(state_dir, repo)
    assert rpp.do_apply(patch.name) == 0
    assert (repo / "target.txt").read_text(encoding="utf-8") == "after\n"


def test_apply_does_not_touch_a_queue_item_for_a_different_patch(rig) -> None:
    repo, state_dir = rig
    patch = _plant(state_dir, repo)
    _write_queue(state_dir, [_queue_item("pending_remediation_other.patch", "hitl-other")])

    assert rpp.do_apply(patch.name) == 0
    queue = json.loads((state_dir / "hitl_queue.json").read_text(encoding="utf-8"))
    assert queue["items"][0]["status"] == "pending"  # untouched — names a different patch


def test_apply_succeeds_even_when_queue_resolution_cannot_import(
    rig, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    # Resolution is best-effort: an import failure inside _resolve_queue_item must not
    # undo or fail an apply whose file-level effect already landed. A fake
    # `agentica_core` package that raises on import, placed at the FRONT of sys.path
    # via GOVERNANCE_ROOT, forces a genuine ImportError instead of relying on Python's
    # module cache (which would otherwise mask a merely-wrong GOVERNANCE_ROOT — the
    # real package, imported by an earlier test, stays importable from sys.path/
    # sys.modules regardless of what this test points GOVERNANCE_ROOT at).
    repo, state_dir = rig
    patch = _plant(state_dir, repo)
    _write_queue(state_dir, [_queue_item(patch.name)])

    fake_gov = tmp_path / "fake_gov"
    (fake_gov / "agentica_core").mkdir(parents=True)
    (fake_gov / "agentica_core" / "__init__.py").write_text(
        "raise ImportError('boom — simulated broken GOVERNANCE_ROOT')\n", encoding="utf-8"
    )
    monkeypatch.setattr(rpp, "GOVERNANCE_ROOT", fake_gov)
    monkeypatch.delitem(sys.modules, "agentica_core", raising=False)
    monkeypatch.delitem(sys.modules, "agentica_core.bushido_engine", raising=False)
    # _resolve_queue_item mutates sys.path in place (sys.path.insert). Swap in a throwaway
    # copy so that mutation reverts with the rest of monkeypatch's teardown, instead of
    # permanently leaving the fake package shadowing the real one for later tests.
    monkeypatch.setattr(sys, "path", list(sys.path))

    assert rpp.do_apply(patch.name) == 0
    assert (repo / "target.txt").read_text(encoding="utf-8") == "after\n"
    queue = json.loads((state_dir / "hitl_queue.json").read_text(encoding="utf-8"))
    assert queue["items"][0]["status"] == "pending"  # resolution silently didn't happen


def test_apply_leaves_the_patch_and_queue_item_untouched_on_a_failed_git_apply(rig) -> None:
    repo, state_dir = rig
    patch = state_dir / "pending_remediation_bad.patch"
    patch.write_text("not a valid diff at all\n", encoding="utf-8")
    _write_queue(state_dir, [_queue_item(patch.name, "hitl-patch-3")])

    assert rpp.do_apply(patch.name) == 1
    assert patch.exists()  # left in place for a retry
    queue = json.loads((state_dir / "hitl_queue.json").read_text(encoding="utf-8"))
    assert queue["items"][0]["status"] == "pending"  # never resolved on a failed apply


def test_resolve_finds_the_filename_token_despite_a_space_in_the_embedded_path(rig) -> None:
    # The context's full path is ".../Order Samurai/state/<name>" — a directory name
    # WITH a space — so the matcher must key off the filename token, not a
    # whitespace-delimited split of the whole "patch=<...>" text.
    repo, state_dir = rig
    patch = _plant(state_dir, repo, "pending_remediation_space_case.patch")
    _write_queue(state_dir, [_queue_item(patch.name, "hitl-patch-4")])

    assert rpp._find_reflex_patch_queue_id(patch.name) == "hitl-patch-4"
